name: Release (Testnet3)

on:
  workflow_dispatch:
  schedule:
    - cron: "25 2 * * *"

jobs:
  release_testnet3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: testnet3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: node ./ci/release_testnet3.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MAC_CERTS: ${{ secrets.MAC_CERTS }}
          MAC_CERTS_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          WINDOWS_CERTS: ${{ secrets.WINDOWS_CERTS }}
          WINDOWS_CERTS_PASSWORD: ${{ secrets.WINDOWS_CERTS_PASSWORD }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
